"""Generate a 16-px-only variant of the AgentDeck app icon.

At 128 px and Dock size the master icon (four fanned Artifact cards, see
build_macos_icon.py) reads clearly. At 32 px it's still readable. Downscaled
to 16 px the gaps between the four cards collapse into a single dark blob, so
the layered-deck silhouette is no longer recognizable (see
openspec/changes/establish-agentdeck-product-identity/tasks.md, 3.4).

This script does NOT touch the master artwork, 32 px or larger outputs, or
the in-app sidebar logo (public/icons/32x32.png, which is a copy of the
32 px desktop icon, not the 16 px one). It draws a separate, simplified
artwork (fewer cards, wider gaps, thicker white borders) and uses it ONLY to
replace these three icns slots, editing the existing icon.icns in place:

    is32 + s8mk   (16x16 @1x)
    ic11          (16x16 @2x = 32 physical px)

Every other slot -- ic07/ic08/ic09/ic10/ic13/ic14 (Dock/Launchpad sizes) and
il32/l8mk/ic12 (the 32 px slots) -- is left untouched: this script never
calls remove_media/add_media on those keys, and icnsutil's write() only
serializes whatever bytes are already in memory for a key, so their payload
bytes cannot change.

This assumes icon.icns is already correct going in (i.e. every slot other
than is32/s8mk/ic11 already holds the content it should ship with). If you
need a known-clean starting point, regenerate the whole set from the
untouched master first (`npx tauri icon src-tauri/icons/icon.png`, see
build_macos_icon.py's docstring) before running this script.

Usage:
    python scripts/build_small_icon.py

Inputs:
    src-tauri/icons/icon.icns                existing icns; only its
                                              is32/s8mk/ic11 slots are
                                              replaced, everything else is
                                              carried through unread and
                                              unmodified.
    src-tauri/icons/icon-source-small.png    generated by this script (see
                                              draw_small_source below); safe
                                              to delete and regenerate, it is
                                              not hand-edited artwork.

Outputs:
    src-tauri/icons/icon-source-small.png
    src-tauri/icons/icon.icns   (is32/s8mk/ic11 replaced in place; every
                                 other slot's bytes are unchanged)

Dependencies beyond build_macos_icon.py's Pillow requirement:
    pip install icnsutil
    (used for the legacy is32 PackBits RLE + s8mk raw-mask encoding;
    round-trip-verified byte-identical against the chunks already shipping
    in icon.icns, see task notes)
"""
from __future__ import annotations

import io
import sys
from pathlib import Path

from PIL import Image, ImageDraw

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_macos_icon import CANVAS, compose_squircle_icon  # noqa: E402

try:
    import icnsutil
    from icnsutil.ArgbImage import ArgbImage
except ImportError as error:  # pragma: no cover - environment guard
    raise SystemExit(
        "missing dependency: pip install icnsutil (see script docstring)"
    ) from error

REPO = Path(__file__).resolve().parent.parent
ICON_DIR = REPO / "src-tauri" / "icons"
SOURCE_SMALL = ICON_DIR / "icon-source-small.png"
ICNS_PATH = ICON_DIR / "icon.icns"

# Card colors, sampled from the master artwork's own front/middle/back cards
# so the simplified small-size version stays visually consistent with it.
CARD_COLORS = [
    (32, 7, 126, 255),   # front card (navy)
    (30, 52, 251, 255),  # middle card (blue)
    (142, 1, 252, 255),  # back card (purple)
]

# Fewer cards, wider offsets, and a thicker white gap than the master artwork
# so the fanned-card silhouette survives downscaling to 16 px.
N_CARDS = 3
CARD_SIZE = 520
CORNER_RADIUS = 110
OFFSET = 170  # per-card diagonal offset, both x and y
STROKE = 40  # white halo width between adjacent cards


def draw_small_source() -> Image.Image:
    """Draw the simplified fanned-card artwork used only for the 16 px slots."""
    img = Image.new("RGBA", (CANVAS, CANVAS), (0, 0, 0, 0))
    draw_ctx = ImageDraw.Draw(img)

    total_span = OFFSET * (N_CARDS - 1)
    base_x = (CANVAS - CARD_SIZE) // 2 - total_span // 2
    base_y = (CANVAS - CARD_SIZE) // 2 + total_span // 2

    for i in reversed(range(N_CARDS)):  # back to front
        x = base_x + OFFSET * i
        y = base_y - OFFSET * i
        # White halo first, so the layer underneath keeps a bright edge
        # where the next card in front doesn't fully cover it.
        draw_ctx.rounded_rectangle(
            [x - STROKE, y - STROKE, x + CARD_SIZE + STROKE, y + CARD_SIZE + STROKE],
            radius=CORNER_RADIUS + STROKE,
            fill=(255, 255, 255, 255),
        )
        draw_ctx.rounded_rectangle(
            [x, y, x + CARD_SIZE, y + CARD_SIZE],
            radius=CORNER_RADIUS,
            fill=CARD_COLORS[i],
        )

    bbox = img.getbbox()
    return img.crop(bbox) if bbox else img


def replace_16px_icns_slots(icns_path: Path, raster16: Image.Image, raster32: Image.Image) -> None:
    """Swap only is32/s8mk/ic11 in an existing icns; every other key is left as-is."""
    icns = icnsutil.IcnsFile(str(icns_path))

    for key in ("is32", "s8mk", "ic11"):
        icns.remove_media(key)

    argb16 = ArgbImage(image=raster16)
    icns.add_media(key="is32", data=argb16.rgb_data(compress=True))
    icns.add_media(key="s8mk", data=argb16.mask_data(compress=False))

    png_buf = io.BytesIO()
    raster32.save(png_buf, format="PNG")  # ic11 = 16 px @2x, PNG-embedded per Apple's newer icns format
    icns.add_media(key="ic11", data=png_buf.getvalue())

    tmp_path = icns_path.with_suffix(".icns.tmp")
    icns.write(str(tmp_path))
    tmp_path.replace(icns_path)


def main() -> None:
    small_source = draw_small_source()
    small_source.save(SOURCE_SMALL, format="PNG", optimize=True)
    print(f"wrote {SOURCE_SMALL}  size={small_source.size}")

    wrapped = compose_squircle_icon(SOURCE_SMALL)
    raster16 = wrapped.resize((16, 16), Image.LANCZOS)
    raster32 = wrapped.resize((32, 32), Image.LANCZOS)  # ic11 = 16px @2x

    replace_16px_icns_slots(ICNS_PATH, raster16, raster32)
    print(f"updated {ICNS_PATH}: is32, s8mk, ic11 replaced with the 16 px design;")
    print("every other slot's bytes are untouched")


if __name__ == "__main__":
    main()
